Fix no method matching on IHACRESExpuhNode update_state
The "Bare node creation" test using IHACRESExpuhNode is returning an
error: `MethodError: no method matching update_state`. This is happening
because the commit 775a575f4dfe42fdedc3748fde9618fd117d6b8e changed the
definition of some methods and not all usage of them have changed. It
adds a "!" to the update_state method on IHACRESExpuhNode.jl.